server:
  port: 8083

spring:
  application:
    name: trip-planner-service

  datasource:
    url: jdbc:postgresql://localhost:5432/roadify?currentSchema=trip_planner
    username: roadify
    password: roadify
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: trip_planner
    default-schema: trip_planner
    create-schemas: true
    table: flyway_schema_history_trip_planner

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info
