server:
  # Discovery ortamında portu random seç, gateway Eureka üzerinden bulacak
  port: 0

spring:
  application:
    name: analytics-service

  # Config Server'dan konfigürasyon almak için (prod / docker ortamlarında)
  config:
    import: optional:configserver:http://config-server:8888

  datasource:
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

  flyway:
    enabled: true
    locations: classpath:db.migration

  security:
    oauth2:
      resourceserver:
        jwt:
          # Docker ağı içinde Keycloak konteynerine giden URL (ileride container'a geçtiğinde)
          jwk-set-uri: http://keycloak:8080/realms/roadify/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

roadify:
  analytics:
    kafka-group: roadify-analytics-service
