spring:
  application:
    name: places-service

roadify:
  route-service:
    base-url: http://localhost:8082

  geoapify:
    base-url: https://api.geoapify.com/v2/places
    api-key: "${GEOAPIFY_API_KEY:change-me}"
    timeout-ms: 5000

  overpass:
    base-url: https://overpass-api.de/api/interpreter
